/*
* Action types
*/

// / LEVELS ACTIONS ///
export const LEVEL_UPDATE = "LEVEL_UPDATE";
export const LEVEL_CREATE = "LEVEL_CREATE";
export const FETCH_LEVEL_SUCCESS = "FETCH_LEVEL_SUCCESS";
export const FETCH_LEVEL_BEGIN = "FETCH_LEVEL_BEGIN";
export const FETCH_LEVEL_FAILURE = "FETCH_LEVEL_FAILURE";
