/*
* Action types
*/

// / LEVELS ACTIONS ///
export const LEVEL_UPDATE = "LEVEL_UPDATE";
export const LEVEL_CREATE = "LEVEL_CREATE";
export const FETCH_LEVEL_SUCCESS = "FETCH_LEVEL_SUCCESS";
export const FETCH_LEVEL_BEGIN = "FETCH_LEVEL_BEGIN";
export const FETCH_LEVEL_FAILURE = "FETCH_LEVEL_FAILURE";

// / MEMBER ACTIONS ///

export const MEMBER_UPDATE = "MEMBER_UPDATE";
export const MEMBER_CREATE = "MEMBER_CREATE";
export const FETCH_MEMBERS_SUCCESS = "FETCH_MEMBERS_SUCCESS";
export const FETCH_MEMBERS_BEGIN = "FETCH_MEMBERS_BEGIN";
export const FETCH_MEMBERS_FAILURE = "FETCH_MEMBERS_FAILURE";
